version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devdojo_maratona_data:/var/lib/mysql

  mysql-exercicios:
    image: mysql
    container_name: mysql-exercicios
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - exercicios_data:/var/lib/mysql

volumes:
  devdojo_maratona_data:
  exercicios_data: